import type { ProductReview } from "./types"

export const DEFAULT_REVIEWS: ProductReview[] = [
  // 1: Kit Pincéis Profissional 12 Peças
  {
    id: "rev-1-1",
    productId: 1,
    productSlug: "kit-pinceis-profissional-12-pecas",
    productName: "Kit Pincéis Profissional 12 Peças",
    authorName: "Camila Rocha",
    authorLocation: "São Paulo - SP (Lojista)",
    rating: 5,
    title: "Qualidade impecável e saída muito rápida!",
    comment:
      "As cerdas são extremamente macias e não soltam fios nem após a higienização. O estojo tem uma apresentação super requintada para expor na vitrine. Comprei 15 kits para testar e vendi tudo em menos de 8 dias com margem de 120%!",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 24,
    createdAt: "2026-02-14T14:32:00.000Z",
  },
  {
    id: "rev-1-2",
    productId: 1,
    productSlug: "kit-pinceis-profissional-12-pecas",
    productName: "Kit Pincéis Profissional 12 Peças",
    authorName: "Patrícia Mendes",
    authorLocation: "Belo Horizonte - MG (Revendedora)",
    rating: 5,
    title: "Excelente acabamento e clientes apaixonadas",
    comment:
      "O produto surpreendeu muito pela qualidade das cerdas sintéticas. Minhas clientes amaram o cabo fosco e a precisão dos pincéis de esfumar. Já estou montando meu terceiro pedido com a Mimos Atacado.",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 19,
    createdAt: "2026-02-28T09:15:00.000Z",
  },
  {
    id: "rev-1-3",
    productId: 1,
    productSlug: "kit-pinceis-profissional-12-pecas",
    productName: "Kit Pincéis Profissional 12 Peças",
    authorName: "Renata Silveira",
    authorLocation: "Curitiba - PR (Maquiadora & Revenda)",
    rating: 5,
    title: "Custo-benefício imbatível no atacado",
    comment:
      "Uso nos atendimentos profissionais e vendo para minhas alunas de automaquiagem. Todas elogiam a maciez e facilidade para espalhar base e sombra.",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 11,
    createdAt: "2026-03-05T18:40:00.000Z",
  },

  // 2: Esponja de Maquiagem Blender
  {
    id: "rev-2-1",
    productId: 2,
    productSlug: "esponja-maquiagem-blender",
    productName: "Esponja de Maquiagem Blender",
    authorName: "Bruna Alves",
    authorLocation: "Rio de Janeiro - RJ",
    rating: 5,
    title: "Cresce de tamanho quando molha, maciez surreal!",
    comment:
      "Esponja de excelente densidade. Quando molhada dobra de tamanho e fica ultra macia, não absorve produto à toa. Coloco no balcão da loja como item de impulso e o giro é absurdo!",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 31,
    createdAt: "2026-02-10T11:20:00.000Z",
  },
  {
    id: "rev-2-2",
    productId: 2,
    productSlug: "esponja-maquiagem-blender",
    productName: "Esponja de Maquiagem Blender",
    authorName: "Amanda Costa",
    authorLocation: "Goiânia - GO (Revenda Online)",
    rating: 5,
    title: "Giro super rápido e preço excelente",
    comment:
      "Peguei a faixa de 48 unidades para aproveitar o desconto progressivo. Valeu cada centavo, já recomprei mais 100 unidades.",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 16,
    createdAt: "2026-02-22T16:05:00.000Z",
  },

  // 3: Sérum Facial Vitamina C
  {
    id: "rev-3-1",
    productId: 3,
    productSlug: "serum-facial-vitamina-c",
    productName: "Sérum Facial Vitamina C",
    authorName: "Mariana Fonseca",
    authorLocation: "Campinas - SP (Estética & Cosméticos)",
    rating: 5,
    title: "Absorção rápida, toque sequinho e resultado iluminador",
    comment:
      "Textura levinha que não pesa na pele oleosa. O conta-gotas funciona perfeitamente e o frasco tem visual bem dermocosmético premium. As clientes adoram!",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 27,
    createdAt: "2026-02-17T13:45:00.000Z",
  },
  {
    id: "rev-3-2",
    productId: 3,
    productSlug: "serum-facial-vitamina-c",
    productName: "Sérum Facial Vitamina C",
    authorName: "Letícia Prado",
    authorLocation: "Salvador - BA (Lojista)",
    rating: 5,
    title: "Campeão de vendas na categoria skincare",
    comment:
      "Vitamina C é o item que mais sai na minha loja de cosméticos. A Mimos Atacado entrega muito bem embalado com plástico bolha reforçado. Nota 10!",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 18,
    createdAt: "2026-03-02T10:10:00.000Z",
  },

  // 4: Protetor Solar Facial FPS 50
  {
    id: "rev-4-1",
    productId: 4,
    productSlug: "protetor-solar-facial-fps-50",
    productName: "Protetor Solar Facial FPS 50",
    authorName: "Jéssica Lima",
    authorLocation: "Fortaleza - CE (Revendedora)",
    rating: 5,
    title: "Toque seco de verdade, não esfarela!",
    comment:
      "Aqui no Ceará a procura por protetor solar com toque seco é constante. Esse produto entrega um acabamento matte sem deixar resíduo branco. Vende o ano inteiro.",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 35,
    createdAt: "2026-02-05T15:20:00.000Z",
  },
  {
    id: "rev-4-2",
    productId: 4,
    productSlug: "protetor-solar-facial-fps-50",
    productName: "Protetor Solar Facial FPS 50",
    authorName: "Fernanda Barbosa",
    authorLocation: "Recife - PE (Loja de Variedades)",
    rating: 5,
    title: "Margem de lucro excelente",
    comment:
      "Comprando no atacado da Mimos consigo revender a preço competitivo e ainda ter mais de 100% de margem. Clientes voltam para recomprar.",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 14,
    createdAt: "2026-02-26T17:30:00.000Z",
  },

  // 5: Perfume Feminino Floral 100ml
  {
    id: "rev-5-1",
    productId: 5,
    productSlug: "perfume-feminino-floral-100ml",
    productName: "Perfume Feminino Floral 100ml",
    authorName: "Aline Castro",
    authorLocation: "Maceió - AL (Revendedora)",
    rating: 5,
    title: "Frasco maravilhoso e fixação incrível",
    comment:
      "Fragrância elegante, doce na medida certa e com projeção marcante. O frasco é pesado e tem tampa de alta qualidade. Faz muito sucesso para presentes.",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 22,
    createdAt: "2026-02-12T08:50:00.000Z",
  },
  {
    id: "rev-5-2",
    productId: 5,
    productSlug: "perfume-feminino-floral-100ml",
    productName: "Perfume Feminino Floral 100ml",
    authorName: "Débora Duarte",
    authorLocation: "Cuiabá - MT (Boutique de Cosméticos)",
    rating: 5,
    title: "Alta procura e ótima apresentação",
    comment:
      "Coloquei um frasco provador na loja e as clientes compram na hora após sentir o cheiro. Recomendo muito para quem revende perfumes!",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 13,
    createdAt: "2026-03-01T14:12:00.000Z",
  },

  // 6: Óleo Capilar Reparador
  {
    id: "rev-6-1",
    productId: 6,
    productSlug: "oleo-capilar-reparador",
    productName: "Óleo Capilar Reparador",
    authorName: "Sabrina Pires",
    authorLocation: "Campo Grande - MS (Espaço da Beleza)",
    rating: 5,
    title: "Cheiro de salão fino e brilho instantâneo",
    comment:
      "Não pesa nos fios finos e controla o frizz perfeitamente. Uso nas finalizações das minhas clientes e muitas já levam o vidro para casa.",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 20,
    createdAt: "2026-02-18T19:25:00.000Z",
  },
  {
    id: "rev-6-2",
    productId: 6,
    productSlug: "oleo-capilar-reparador",
    productName: "Óleo Capilar Reparador",
    authorName: "Tatiana Fernandes",
    authorLocation: "João Pessoa - PB (Revenda)",
    rating: 5,
    title: "Perfeito para vendas casadas",
    comment:
      "Produto coringa que todo mundo compra junto com kit de maquiagem ou skincare. Ótimo lucro unitário.",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 12,
    createdAt: "2026-03-04T12:00:00.000Z",
  },

  // 7: Kit de maquiagem 40 itens - Para Revender
  {
    id: "rev-7-1",
    productId: 7,
    productSlug: "kit-de-maquiagem-40-itens-para-revender",
    productName: "Kit de maquiagem 40 itens - Para Revender",
    authorName: "Juliana Martins",
    authorLocation: "Porto Alegre - RS (Lojista)",
    rating: 5,
    title: "O melhor investimento para quem quer começar a revender!",
    comment:
      "Vem super completo com itens que as clientes procuram todo dia: batons, sombras, bases e esponjas. Vendi peça por peça individualmente e lucrei mais de R$ 350,00 só nesse kit!",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 42,
    createdAt: "2026-02-08T10:40:00.000Z",
  },
  {
    id: "rev-7-2",
    productId: 7,
    productSlug: "kit-de-maquiagem-40-itens-para-revender",
    productName: "Kit de maquiagem 40 itens - Para Revender",
    authorName: "Vanessa Souza",
    authorLocation: "Ribeirão Preto - SP (Revenda de Maquiagem)",
    rating: 5,
    title: "Itens novinhos, lacrados e com validade longa",
    comment:
      "Chegou super rápido aqui no interior de SP. Todos os produtos bem embalados e protegidos. Já estou no meu terceiro pedido de kits atacado.",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 28,
    createdAt: "2026-02-24T15:15:00.000Z",
  },
  {
    id: "rev-7-3",
    productId: 7,
    productSlug: "kit-de-maquiagem-40-itens-para-revender",
    productName: "Kit de maquiagem 40 itens - Para Revender",
    authorName: "Carla Nogueira",
    authorLocation: "Brasília - DF",
    rating: 5,
    title: "Surpreendeu pela variedade",
    comment:
      "Cores de alta saída, nada encalhado. Montei kits menores de presente e vendi tudo na mesma semana.",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 17,
    createdAt: "2026-03-08T11:20:00.000Z",
  },

  // 8: Kit de esponjas Beauty Blender 360º - Kit com 10
  {
    id: "rev-8-1",
    productId: 8,
    productSlug: "kit-esponja-coxinha-12-unidades-beauty-blender",
    productName: "Kit de esponjas Beauty Blender 360º - Kit com 10",
    authorName: "Carolina Dias",
    authorLocation: "Florianópolis - SC",
    rating: 5,
    title: "Super macias e com formato perfeito para cantinhos do olho",
    comment:
      "A ponta fina facilita muito a aplicação de corretivo e a base redonda esfuma sem deixar marcas. Pacote com 10 sai com preço unitário excelente no atacado.",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 25,
    createdAt: "2026-02-11T14:50:00.000Z",
  },
  {
    id: "rev-8-2",
    productId: 8,
    productSlug: "kit-esponja-coxinha-12-unidades-beauty-blender",
    productName: "Kit de esponjas Beauty Blender 360º - Kit com 10",
    authorName: "Larissa Ribeiro",
    authorLocation: "Santos - SP (Revendedora)",
    rating: 5,
    title: "Revendo no balcão da loja e sai muito rápido",
    comment:
      "Produto essencial que toda mulher que usa maquiagem troca a cada 2 ou 3 meses. Giro contínuo garantido!",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 15,
    createdAt: "2026-02-27T16:45:00.000Z",
  },

  // 9: Kit de maquiagem 38 itens com acessórios extras
  {
    id: "rev-9-1",
    productId: 9,
    productSlug: "kit-de-maquiagem-38-itens-com-acessorios-extras-para-revender",
    productName: "Kit de maquiagem 38 itens com acessórios extras - Para Revender",
    authorName: "Thaís Moreira",
    authorLocation: "Manaus - AM (Empreendedora da Beleza)",
    rating: 5,
    title: "Kit completo de altíssima qualidade!",
    comment:
      "Os pincéis e acessórios que vêm junto com as maquiagens agregam muito valor na hora da revenda. Consegui montar combos que as clientes disputaram.",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 38,
    createdAt: "2026-02-16T17:10:00.000Z",
  },
  {
    id: "rev-9-2",
    productId: 9,
    productSlug: "kit-de-maquiagem-38-itens-com-acessorios-extras-para-revender",
    productName: "Kit de maquiagem 38 itens com acessórios extras - Para Revender",
    authorName: "Priscila Vieira",
    authorLocation: "Natal - RN (Lojista)",
    rating: 5,
    title: "Margem de revenda fantástica",
    comment:
      "Aproveitei a promoção de quantidade e peguei 3 kits. Já estou quase zerando o estoque. Atendimento da Mimos pelo WhatsApp é nota 10!",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 21,
    createdAt: "2026-03-03T09:30:00.000Z",
  },

  // 10: Esponja Coxinha para Maquiagem PL02 – Pcte c/ 12 unidades
  {
    id: "rev-10-1",
    productId: 10,
    productSlug: "kit-esponja-coxinha-12-unidades",
    productName: "Esponja Coxinha para Maquiagem PL02 – Pcte c/ 12 unidades",
    authorName: "Michele Santos",
    authorLocation: "Uberlândia - MG (Revendedora)",
    rating: 5,
    title: "Pacote econômico, qualidade espetacular",
    comment:
      "Vem em embalagem prática, as esponjas não esfarelam e têm ótima elasticidade. Vendi todas as 12 unidades separadas em 4 dias.",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 23,
    createdAt: "2026-02-19T11:00:00.000Z",
  },
  {
    id: "rev-10-2",
    productId: 10,
    productSlug: "kit-esponja-coxinha-12-unidades",
    productName: "Esponja Coxinha para Maquiagem PL02 – Pcte c/ 12 unidades",
    authorName: "Gabriela Borges",
    authorLocation: "Sorocaba - SP (Salão & Loja)",
    rating: 5,
    title: "Recomendo muito a Mimos Atacado",
    comment:
      "Comprei para abastecer a bancada do salão e disponibilizar na recepção para as clientes comprarem. Foi um sucesso absoluto!",
    isVerifiedPurchase: true,
    isApproved: true,
    helpfulCount: 14,
    createdAt: "2026-03-06T15:40:00.000Z",
  },
]
